repos:
  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format --output=none --set-exit-if-changed
        language: system
        types: [dart]

      - id: flutter-analyze
        name: Flutter Analyze
        entry: env -u GIT_DIR -u GIT_WORK_TREE flutter analyze --no-fatal-infos
        language: system
        types: [dart]
        pass_filenames: false
